#!/usr/bin/env python3
"""Emit the lane x mutation enablement matrix (rows = lanes, cols = units).

Reads only artefacts the two sides own -- the ledger, the spec registry and
each lane's committed mutant manifest.  Nothing here is hand-maintained, so the
matrix cannot drift from the ledger the way a hand-typed table does.

Cell vocabulary (see LEGEND):

  REC    the lane's committed mutant corpus contains a mutant for this unit.
         The only cell that supports a head-to-head rate.
  expr   the lane's OWN S8_expressibility row says its surface carries this
         obligation, but no mutant exists.  A corpus gap in THAT LANE -- an
         action item, not a limitation.
  n/a    the model has no construct of this kind (constitutional), or the
         check is contractually the writer's (delegation).  A scope claim.
  rep    the register classifies the defect as model-REPAIRED (P2 hard error).
         P2 mutants are never generated, so this can never become a rate.
  noop   noop by construction: nothing to forbid (e.g. a zero-trip loop).
  blk    OUR base kernels lack the construct.  Not a lane's gap and not a model
         claim -- a hole in the benchmark.

Writes nothing unless --out PATH is given.
"""
from __future__ import annotations

import argparse
import collections
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / "schema" / "mutation-correspondence.json"
REGISTRY = ROOT / "choreo" / "raw" / "spec_registry.json"
MUTATIONS = ROOT / "choreo" / "mutations.py"

LANES = ("choreo", "triton", "mlir-linalg", "mlir-low", "iree")
CLASSES = ("M1", "M2", "M3", "M4")

LEGEND = [
    ("REC", "mutant recorded in the lane's committed corpus (supports a rate)"),
    ("expr", "lane's own S8 says expressible; no mutant -> that lane's gap"),
    ("n/a", "no construct of this kind (scope claim), or delegated"),
    ("rep", "model-repaired (P2 hard error); mutants never generated"),
    ("noop", "noop by construction -- nothing to forbid"),
    ("blk", "OUR suite lacks the base case -- nobody can generate it"),
]

_STATUS = {
    "recorded": "REC",
    "expressible-not-recorded": "expr",
    "constitutional-n-a": "n/a",
    "blocked-by-suite": "blk",
    "uncompared": "u",
}


def load():
    ledger = json.loads(LEDGER.read_text())
    reg = {s["spec_id"]: s
           for s in json.loads(REGISTRY.read_text())["specs"]}
    spec = importlib.util.spec_from_file_location("_mut", MUTATIONS)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return ledger, reg, set(mod.NOOP_BY_CONSTRUCTION)


def choreo_cell(unit: dict, reg, noop) -> str:
    c = unit["choreo"]
    if c["realized"]:
        return "REC"
    s = reg[unit["unit"]]
    if "MISSING SURFACE" in (s["note"] or ""):
        return "blk"
    if s["prohibition"] == "repaired":
        return "rep"
    if unit["unit"] in noop:
        return "noop"
    if s["prohibition"] == "absent":
        return "n/a"
    if not s["admissible"]:
        return "noop"
    return "expr"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--legend", action="store_true")
    args = ap.parse_args()

    ledger, reg, noop = load()
    units = ledger["units"]
    by_class = collections.defaultdict(list)
    for u in units:
        by_class[u["class"]].append(u)
    for cls in by_class:
        by_class[cls].sort(key=lambda u: int(u["unit"].split(".")[1]))

    out: list[str] = []
    out.append("# Lane x mutation enablement matrix")
    out.append("")
    out.append("Generated by `schema/emit_enablement_matrix.py` from")
    out.append("`schema/mutation-correspondence.json`. Rows are lanes, columns")
    out.append("are mutation units; the cell is the enablement status.")
    out.append("")
    if args.legend:
        out.append("| cell | meaning |")
        out.append("|---|---|")
        for k, v in LEGEND:
            out.append(f"| `{k}` | {v} |")
        out.append("")

    tally = collections.Counter()
    for cls in CLASSES:
        us = by_class.get(cls, [])
        if not us:
            continue
        out.append(f"## {cls} — {len(us)} units")
        out.append("")
        # two header rows so the class prefix is not repeated 26 times
        out.append("| lane | " + " | ".join(
            f"{cls}.{u['unit'].split('.')[1]}" for u in us) + " |")
        out.append("|" + "---|" * (len(us) + 1))
        for lane in LANES:
            cells = []
            for u in us:
                if lane == "choreo":
                    cell = choreo_cell(u, reg, noop)
                else:
                    cell = _STATUS.get(u["lanes"][lane]["status"],
                                       u["lanes"][lane]["status"])
                cells.append(cell)
                tally[(lane, cls, cell)] += 1
            out.append(f"| **{lane}** | " + " | ".join(cells) + " |")
        out.append("")

    # per-lane roll-up
    out.append("## Roll-up")
    out.append("")
    out.append("`carries` = REC + expr (the lane's own S8 says the surface")
    out.append("carries the obligation). `covered` = REC only.")
    out.append("")
    out.append("| lane | " + " | ".join(f"{c} REC" for c in CLASSES)
               + " | REC | expr | n/a | rep/noop | blk | carries |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for lane in LANES:
        per = [tally[(lane, c, "REC")] for c in CLASSES]
        rec = sum(per)
        expr = sum(tally[(lane, c, "expr")] for c in CLASSES)
        na = sum(tally[(lane, c, "n/a")] for c in CLASSES)
        rn = sum(tally[(lane, c, k)] for c in CLASSES for k in ("rep", "noop"))
        blk = sum(tally[(lane, c, "blk")] for c in CLASSES)
        out.append(f"| **{lane}** | " + " | ".join(str(x) for x in per)
                   + f" | **{rec}** | {expr} | {na} | {rn} | {blk} |"
                   + f" **{rec + expr}** |")
    out.append("")

    text = "\n".join(out)
    if args.out:
        args.out.write_text(text + "\n")
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
