#!/usr/bin/env python3
"""E1 classifier for the choreo lane.

Takes the mutants written by gen_mutants.py and classifies each one into the
`mutant` record of schema/record-schema.json:

    outcome in {compile, runtime, never, n/a}
    stage   in {compile, runtime}
    manifest in {corrupts, noop}

Attribution — the part that is easy to get wrong
------------------------------------------------
A choreo kernel's `main()` already contains an independent host-side reference
check that calls `choreo::choreo_assert(...)`. That check is the ground-truth
ORACLE required by specs §7 — it is NOT choreo's detector.

There are FOUR distinct sources of assertion output, spread over TWO prefixes
and TWO streams. The prefix alone does not separate them, and neither does the
stream alone:

    "choreo runtime check failed: ..."   stderr   source A (host form)
                                                  AND source LIB (ungated)
    "choreo assertion failed: ..."       stdout   source A (device form),
                                                  source B, and source C

  A  generated ASSESSMENTS — **the assessor; an A firing is a detection.**
     `CreateAssessment` in lib/semacheck.cpp, emitted by
     `CuteCodeGen::EmitPreSiteAssertions` / `EmitPostSiteAssertions` at
     lib/Target/GPU/cute_codegen.cpp:11789 / :11801. Both begin
     `if (CCtx().DisableRuntimeCheck()) return;`, so A is GATED by
     --disable-runtime-check (equivalently -rtc=none). A has TWO emission forms,
     because per the comment at cute_codegen.cpp:11805 "HOIST_SITE and USE_SITE
     assertions are emitted in device code using choreo_assert (printf-based)
     because std::cerr is not available on device":
         A-host    runtime_check(...)  -> "choreo runtime check failed: " stderr
         A-device  choreo_assert(...)  -> "choreo assertion failed: "     stdout
     Both forms append the source location (`ar.message << ", " << ar.loc`), so
     A is identified by the suffix `, <path>:<line>.<col>` — see RE_ASSESSMENT.
     ONE gated family has no suffix and is matched separately: `shape
     inconsistent on the <ord> parameter (...)` (RE_SHAPE_CHECK). It is the
     commonest detection in this suite, so missing it is expensive.
     Do NOT enumerate A by message template: a template list only covers the
     assessments this semacheck version happens to create, and the location
     suffix is generated by the emitter itself, so it is complete by
     construction. A hand-written seven-template list previously matched ZERO
     lines across 160 real logs.
  B  runtime-LIBRARY bounds check. `ArrayProxy::operator[]` at
     runtime/choreo.h:394/405/782/791/884, message bare "Index out of bounds".
     NOT gated: verified by diffing a retained det.sh against its off.sh, which
     contain byte-identical call sites. B is a defensive container check, not
     assessor output, so it does NOT count as a detection.
  C  the §7 ORACLE. User-written `assert` BIF, passed through at
     cute_codegen.cpp:8359. Closed vocabulary — see RE_ORACLE_MSG.
  LIB runtime-HEADER sanity checks, ungated, and sharing A-host's prefix. Seven
     literals in runtime/choreo.h, all beginning `at::Tensor ` or `[choreo-rt]`:
     is undefined / must be a CUDA tensor / must be contiguous / rank mismatch /
     dtype mismatch / failed to allocate memory / failed to free memory.
     Matching the bare "choreo runtime check failed" prefix and calling it a
     detection would credit an OOM or a non-contiguous input tensor to the
     assessor, so RE_LIB_SANITY is tested BEFORE the prefix fallback.

Counting B, C or LIB as detected would inflate the detection matrix (S1) with
work that is not the assessor's. Conversely, matching C by NEGATION ("anything
that isn't template A1") silently absorbs A's other families as oracle-only and
records real detections as misses, which DEFLATES S2. Both classifiers here
therefore match A, B, C and LIB POSITIVELY and leave an `unattributed` bucket
for anything unrecognized, so a new message surfaces instead of being credited
to the harness.

B also fires from INSIDE the oracle arm, because the §7 comparison indexes its
own operands through ArrayProxy (`out[i][j][k]` at
benchmark/choreo/layer_normalization/1_bert_32x512x768_768_768.co:90,
`output[h][w][c]` at benchmark/choreo/softmax/common.hpp:70). That is why the
oracle arm records `oracle_caught` separately: a `manifest=corrupts` verdict
resting on B is not fully independent of choreo-provided code, and the record
should say so rather than hide it.

The oracle build
----------------
`-rtc=none` suppresses choreo's generated obligation checks (source A) while
leaving the kernel's own `choreo_assert` reference check (source C) and the
inlined runtime header's checks (source B and LIB) intact. Running the mutant
under `-rtc=none` is therefore exactly the specs §7 manifest check:

    oracle fails / aborts / no "Passed."  -> manifest = corrupts  (real defect)
    oracle prints "Passed."               -> manifest = noop      (discard, §11.1)

`-rtc=none` and `--disable-runtime-check` are EQUIVALENT, proven at the
generated-code level rather than assumed: over 20 mutants the two builds are
byte-identical after normalizing the `/tmp/<digits>_<digits>` staging directory.
Both reduce `runtime_check(` sites 14 -> 9 and leave `choreo_assert(` sites
39 -> 39 unchanged; the 5 removed sites are all `shape inconsistent on the Nth
parameter (...)`. So the flag removes only source A's host form and touches
neither source B nor source C. ORACLE_FLAGS keeps `-rtc=none`; the choice is
cosmetic, and the equivalence is now evidence rather than an assumption.

Usage:
  run_e1.py [--jobs N] [--limit N] [--only CLASS] [--out FILE]
"""

from __future__ import annotations

import argparse
import collections
import concurrent.futures as cf
import json
import os
import re
import subprocess
import sys
import time

import toolchain                                           # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))          # benchmark2/choreo
B2 = os.path.dirname(HERE)                                 # benchmark2/
REPO = os.path.dirname(B2)                                 # svn-artifacts/
CHOREO = os.path.join(REPO, "croqtile", "build-release", "choreo")
MANIFEST_IN = os.path.join(HERE, "raw", "mutant_manifest.json")
RAW = os.path.join(HERE, "raw")
ORACLE_POLICY = os.path.join(RAW, "oracle_policy.json")

TOOLCHAIN = "choreo"
# Pinned suite invocation (manifest §3): --stats -es --max-local-mem-capacity=2000000 -t cute.
#
# The cap is NOT optional for E1. Measured: the UNMUTATED matmul base kernel
# fails to compile at the 2048-byte default (exit=4, "Used: 98304 bytes,
# Limit: 2048 bytes") and compiles cleanly at 2000000. Classifying correct code
# as "compile-detected" would be nonsense, so E1 uses the pinned cap for both
# builds. Consequence, recorded for the manifest: M3 spec-3 mutants are measured
# against a 2,000,000-byte local-memory budget and against the shared-memory
# device limit (48 KB default / 98304 B with the dynamic attribute), not against
# the 2048-byte default.
CAP = "--max-local-mem-capacity=2000000"
COMPILE_FLAGS = ["-gs", "-t", "cute", "-kt", CAP]
ORACLE_FLAGS = ["-gs", "-t", "cute", "-kt", CAP, "-rtc=none"]

# Categories whose reference check is compiled out unless -D__CHECK__ is given
# (their common.h/common.hpp wraps the cpu_* comparison in `#ifdef __CHECK__`).
# Without this the oracle silently does nothing and every mutant looks like a
# clean pass -> false `noop`. The generated script forwards EXTRA_TARGET_CFLAGS
# into nvcc, so that is how the flag is delivered.
#
# __CHECK__ is enabled for BOTH builds on purpose: the detector build then runs
# choreo's obligation checks *and* the oracle, the oracle build runs only the
# oracle, and the difference is attributable to choreo alone. choreo's entry
# checks fire before any computation, so they cannot be masked by the oracle.
#
# Whether the flag is actually used is decided per (category, case) by
# --calibrate, because some built-in references are themselves wrong (measured:
# the UNMUTATED softmax base aborts with "choreo assertion failed: Test Failed",
# so its cpu_softmax1 reference disagrees with the kernel's own layout). Enabling
# __CHECK__ there would mark every mutant `corrupts` regardless of the defect.
GATED_CHECK = {"conv2d", "matmul", "max_pool2d", "reshape", "softmax"}

T_COMPILE = 300      # choreo front end is ~0.02 s; this is headroom
T_EXECUTE = 900      # nvcc build + run is ~12 s per mutant

RE_RTC = re.compile(r"choreo runtime check failed")
RE_ASSERT = re.compile(r"choreo assertion failed")

# ---------------------------------------------------------------------------
# THREE sources of assertion output, split across TWO prefixes and TWO streams.
# ---------------------------------------------------------------------------
# This was gotten wrong once already, in a way that looked right. The first
# model said all three sources print "choreo assertion failed" on stdout and
# that only the message text separates them. Measured against the 160 retained
# raw/e1_logs/*/*.run.log files that is false, so here is what the logs and the
# codegen actually say.
#
#   A. GENERATED ASSESSMENTS -- the assessor, the paper's mechanism, and the
#      only source that evidences a static-analysis verdict. GATED: both
#      emission sites in CuteCodeGen::Emit{Pre,Post}SiteAssertions
#      (cute_codegen.cpp:11789/11801) begin `if (CCtx().DisableRuntimeCheck())
#      return;`. A has TWO emission forms, and which one you get depends on
#      whether the site is host or device code:
#
#        A-host   `choreo::runtime_check(...)`  -> STDERR, prefix
#                 "choreo runtime check failed: "
#        A-device `choreo::choreo_assert(...)`   -> STDOUT, prefix
#                 "choreo assertion failed: "
#
#      The device form exists because, per the comment at cute_codegen.cpp:11805,
#      "HOIST_SITE and USE_SITE assertions are emitted in device code using
#      choreo_assert (printf-based) because std::cerr is not available on
#      device." Both forms append the source location into the message
#      (`ar.message << ", " << ar.loc`), so both end with `, <path>:<line>.<col>`.
#
#      In the E1 default-flag corpus only A-host occurs: 16 "runtime check
#      failed" lines, all in the det arm, zero in the off arm, and zero
#      "assertion failed" lines carrying a location suffix. A-device is NOT
#      hypothetical, though -- it is what the forced-flag probe produces. Under
#      `-rtc=all --disable-assert-hoist`, 8 of the 37 `never` mutants fire
#      A-device on stdout with the suffix intact, e.g.
#        /tmp/.../choreo.h:221: choreo assertion failed: The 1st index ` (k - 1) `
#        of element access 'bias' should be greater than or equal to 0,
#        /tmp/never_8bd25ddf/k.co:34.102
#      Both matchers are therefore load-bearing, just on different corpora.
#
#   B. RUNTIME-LIBRARY BOUNDS CHECK -- ArrayProxy::operator[] in
#      runtime/choreo.h:394/405/782/791/884, message is the bare literal
#      "Index out of bounds", stdout, NO location suffix. NOT gated: verified by
#      counting call sites in the retained scripts (M2.s4.ln1.caller.out
#      det.sh=12 off.sh=12; M2.s1.ln1.caller.scale det.sh=12 off.sh=12). This
#      is a defensive check inside the container accessor, not assessor output.
#
#   C. §7 ORACLE -- user-written `assert` BIF calls in benchmark/choreo, passed
#      through at cute_codegen.cpp:8359. stdout, NO location suffix. NOT gated.
#      The harness's own numeric reference check: ground truth, never a
#      detection.
#
# WHY THE LOCATION SUFFIX, NOT A TEMPLATE LIST, IDENTIFIES A ON STDOUT.
# An earlier version of this file enumerated seven message templates read off
# the CreateAssessment call sites (semacheck.cpp:449, 605-634, 1035, 1090,
# 1996-2004, 863; gpu_adapt.hpp:675) and matched them against the
# "choreo assertion failed" prefix. That regex matched ZERO lines in 160 logs,
# for two independent reasons: the templates are emitted under the runtime_check
# prefix, not the assertion prefix; and one of the seven was wrong anyway (the
# DMA template renders `'from'(` with no space before the paren). A template
# list is also inherently incomplete -- it can only cover assessments this
# version of semacheck happens to create. The location suffix is generated by
# the emitter itself (`<< ", " << ar.loc`) and so is present for EVERY
# assessment regardless of which template produced it. Match on that.
#
# WHY B MUST NOT BE FOLDED INTO C. The oracle reads its own operands through
# ArrayProxy (`out[i][j][k]`, layer_normalization/1_bert:90; `output[h][w][c]`,
# softmax/common.hpp:70), so a mutated index can trip source B from INSIDE the
# oracle arm. A negative-lookahead matcher ("anything that is not A is oracle")
# silently absorbs those as oracle-only, which both (i) hides that the manifest
# verdict was not independent of choreo, and (ii) mislabels a choreo-provided
# bounds check as the harness's work. B therefore gets its own label. Measured:
# 4 oracle-arm rows in this suite rest on B.
#
# WHY A MUST NOT BE FOLDED INTO C EITHER. Without it a mutant whose assessment
# fires is recorded detector="oracle", outcome="never" -- choreo charged with
# missing a bug it caught. Measured consequence at -rtc=all
# --disable-assert-hoist: 8 of the 37 `never` mutants fire an assessment (see
# raw/c2_probe_groundtruth.json), so S2 is configuration-dependent and the
# default-level figure understates the assessor.
#
# THOSE 8 ARE NOT ONE PHENOMENON. Comparing the hoist_on and hoist_off arms of
# the forced-flag probe separates two mechanisms that the single-flag-set
# fixture conflates:
#   (a) 2 mutants fire in BOTH arms -> recovered by `-rtc=all` alone. The
#       assessment was simply never EMITTED at the default check level. This is
#       an emission-policy consequence, working as designed.
#       M1.s3.ln1.bias, M1.s3.ln3.bias.
#   (b) 6 mutants fire only with `--disable-assert-hoist` -> the assessment WAS
#       emitted but placed where it cannot fire. This is a genuine codegen
#       HOISTING DEFECT, and it is fixable.
#       M1.s1.ln3.mask, M1.s2.ln1.out, M1.s2.ln1.scale, M1.s2.ln3.scale,
#       M1.s5.ln1.chunk, M2.s4.ln1.out.
# All 8 are layer_normalization (7 M1 + M2.s4.ln1.out). Set (b) matches the
# HOISTING_DEFECT promotions in raw/never_attribution.json exactly (6/6).
# Reporting all 8 as "policy" would understate a real bug by 6 detections.
#
# The location suffix is the discriminator for source A on either prefix.
RE_ASSESSMENT = re.compile(
    r"choreo (?:runtime check|assertion) failed: .*\.co:\d+\.\d+\s*$",
    re.MULTILINE,
)
# A SECOND source-A family carries NO location suffix, so RE_ASSESSMENT does not
# see it: `shape inconsistent on the <ord> parameter ('<name>', dim: <n>):
# expect: <n>, but got <n>.` It is emitted via runtime_check at
# cute_codegen.cpp:9965+ and is nonetheless GATED -- measured on 20 mutants, a
# base build has 5 such sites and a --disable-runtime-check build has 0. In this
# suite it is the commonest detection of all: 10 of the 16 source-A log lines.
RE_SHAPE_CHECK = re.compile(
    r"choreo runtime check failed: shape inconsistent on the \w+ parameter \("
)
# UNGATED LIBRARY SANITY CHECKS. These share source A's host prefix
# ("choreo runtime check failed: ") but are NOT assessments: they live in
# runtime/choreo.h, survive --disable-runtime-check, and report harness or
# allocator faults rather than a static-analysis verdict. The complete closed set
# (`grep -rhoE 'runtime_check\([^;]{0,220}' runtime/ | grep -oE '"[^"]{3,90}'`,
# cross-checked by diffing base vs --disable-runtime-check codegen over 20
# mutants) is seven literals, all beginning `at::Tensor ` or `[choreo-rt]`:
#   at::Tensor is undefined.          at::Tensor must be a CUDA tensor.
#   at::Tensor must be contiguous.    at::Tensor rank mismatch: expect ...
#   at::Tensor dtype mismatch.        [choreo-rt] failed to allocate memory.
#   [choreo-rt] failed to free memory.
# Matching the bare prefix and calling it a detection -- which is what an
# earlier version of this file did -- would credit an allocation failure or a
# non-contiguous input tensor to the assessor. No such line occurs in the 160
# retained logs, so this is a latent bug rather than a measured error, but it is
# the same defect as the negative-lookahead oracle matcher and gets the same
# treatment: enumerate positively.
RE_LIB_SANITY = re.compile(
    r"choreo runtime check failed: (?:at::Tensor |\[choreo-rt\])"
)
# Source B: bare literal, no trailing detail. Anchored so it cannot match an
# assessment's "Index <n> is out of bounds of the <ord> dimension of array ...,
# <path>:<line>.<col>" -- the two share a prefix but B has no location suffix.
RE_RUNTIME_LIB = re.compile(r"choreo assertion failed: Index out of bounds\s*$",
                            re.MULTILINE)
# Source C: the closed vocabulary of hand-written §7 checks, enumerated from the
# suite (`grep -rho 'choreo_assert([^;]*' benchmark/choreo | grep -o '"[^"]*"'`):
#   85 "values are not equal."   21 "concat mismatch"   19 "batch_norm mismatch"
#   16 "reduce_mean mismatch"     4 "error"              2 "Test Failed"
#    1 "actual != expect"         1 "sampled verification failed"
# Matched POSITIVELY rather than as "not A and not B", because a negative
# matcher turns any unrecognized message into an oracle verdict -- the one
# direction that inflates the harness and deflates choreo. An unmatched message
# falls through to `unattributed` below so it is visible instead of absorbed.
RE_ORACLE_MSG = re.compile(
    r"choreo assertion failed: (?:"
    r"values are not equal\.|concat mismatch|batch_norm mismatch"
    r"|reduce_mean mismatch|Test Failed|actual != expect"
    r"|sampled verification failed|error"
    r")"
)
# Success markers. The suite is NOT consistent about these; all six spellings
# below occur in benchmark/choreo (counts from `grep -rhoE '"[^"]*[Pp]ass[^"]*"'`):
#
#   146  "Passed.\n"            hand-written main(), most categories
#     9  "Test %s Passed!\n"    matmul common.hpp TEST2/TEST3
#     7  " is PASS.\n"          transpose, conv2d-style main()
#     4  "Test %s passed!\n"    softmax common.hpp TEST1/TEST2  (lowercase p)
#     1  "Test Passed\n"
#     1  "Case %s Passed!\n"    matmul common.hpp TEST1
#
# Matching only "Passed." silently marked every transpose base as failing its
# own reference check, which would have voided 10 mutants' manifest verdicts.
RE_PASSED = re.compile(
    r"^Passed\.$"
    r"|^(?:Test|Case)\b.*\bpassed!?$"
    r"|^Test Passed$"
    r"|^.*\bis PASS\.$",
    re.M | re.I)
RE_EXECTIME = re.compile(r"Execution time:\s*(\d+)\s*(?:us|microseconds)")

# Infrastructure failures. These mean the harness could not build or launch the
# program at all, so they carry NO information about detection and must never be
# folded into outcome=never (that would silently corrupt the S1 matrix).
RE_INFRA = re.compile(
    r"fatal error: .*No such file or directory"
    r"|\.exe: No such file or directory"
    r"|cannot find -l"
    r"|CUDA_HOME|CUTE_HOME"
    r"|\[harness\] TIMEOUT"
    r"|No space left on device"
    r"|cudaErrorInsufficientDriver"
    r"|no CUDA-capable device is detected"
)


def infra_failure(text):
    """Return a short reason if the log shows a harness/environment fault."""
    m = RE_INFRA.search(text)
    return m.group(0)[:120] if m else None


def sha1_12(path):
    import hashlib
    with open(path, "rb") as f:
        return hashlib.sha1(f.read()).hexdigest()[:12]


def toolchain_version():
    """Commit the choreo BINARY was built from. See toolchain.py for why this is
    not `git rev-parse HEAD` of the checkout, and run_e2.toolchain_version for
    the shared rationale. E1 defines its own copy only because it does not
    import run_e2; both delegate to the same module, so both agree.
    """
    return toolchain.version()


def local_headers_for(category, suite_dir):
    """Non-.co files a category's kernels #include by bare relative path.

    choreo emits a .cu that does `#include "common.hpp"` and passes
    `-I<directory of the .co file>`, so the header must sit next to the kernel
    being compiled. Categories observed to need this: conv2d and transpose
    (common.h), matmul and softmax (common.hpp).
    """
    d = os.path.join(suite_dir, category)
    if not os.path.isdir(d):
        return []
    return [os.path.join(d, n) for n in sorted(os.listdir(d))
            if not n.endswith(".co") and os.path.isfile(os.path.join(d, n))]


def run(cmd, timeout, logpath, env=None):
    """Run cmd, tee combined output to logpath, return (rc, text).

    stdbuf -o0 -e0 is required: abort() discards buffered stdout, and the
    attribution message is printed on stdout immediately before the abort.
    """
    full = ["stdbuf", "-o0", "-e0"] + cmd
    e = dict(os.environ)
    if env:
        e.update(env)
    try:
        p = subprocess.run(full, capture_output=True, text=True,
                           timeout=timeout, cwd=REPO, errors="replace", env=e)
        text = (p.stdout or "") + (p.stderr or "")
        rc = p.returncode
    except subprocess.TimeoutExpired as ex:
        text = ((ex.stdout or b"").decode("utf-8", "replace") if isinstance(ex.stdout, bytes)
                else (ex.stdout or "")) + \
               ((ex.stderr or b"").decode("utf-8", "replace") if isinstance(ex.stderr, bytes)
                else (ex.stderr or ""))
        text += "\n[harness] TIMEOUT after %ds\n" % timeout
        rc = 124
    with open(logpath, "w") as f:
        f.write(text)
    return rc, text


def compile_stage(src, flags, out_sh, logpath):
    cmd = [CHOREO] + flags + [src, "-o", out_sh]
    rc, text = run(cmd, T_COMPILE, logpath)
    ok = rc == 0 and os.path.exists(out_sh) and os.path.getsize(out_sh) > 0
    return ok, rc, text


def execute_stage(out_sh, logpath, env=None):
    rc, text = run(["bash", out_sh, "--execute"], T_EXECUTE, logpath, env=env)
    return rc, text, infra_failure(text)


def classify_log(text, rc):
    """Return (caught_by, passed) for one execution log.

    `caught_by` is one of:
      detector        source A -- a choreo-generated assessment fired. Either the
                      entry-level `runtime_check` (stderr, before the body runs)
                      or a site `choreo_assert` (stdout, at the access). This is
                      the assessor's verdict and counts as DETECTED.
      runtime_lib     choreo-provided but NOT an assessor output: source B
                      (ArrayProxy's "Index out of bounds") or the ungated
                      `runtime_check` library sanity checks (`at::Tensor ...`,
                      `[choreo-rt] ...`). These survive
                      --disable-runtime-check, so they are present in the oracle
                      arm too and cannot evidence a static verdict. Counted as
                      NOT detected, but reported separately from the oracle so
                      the distinction stays visible.
      oracle          source C -- only the kernel's §7 reference check spoke.
                      NOT detected.
      unattributed    an assertion fired whose message matches none of the known
                      vocabularies. Deliberately NOT folded into `oracle`: doing
                      so would let an unrecognized choreo message silently count
                      as the harness's work. Needs a human look.
      crash           aborted with no attribution message (device-side trap)
      none            nothing fired

    Order matters, and the reason is that the sources share prefixes:
      1. Source A is matched FIRST and POSITIVELY (location suffix, or the
         `shape inconsistent` template). It must precede RE_RTC's bare prefix
         because A-host and the ungated library checks share that prefix.
      2. The library sanity checks are matched before the bare prefix, so an
         allocation failure is not credited to the assessor.
      3. Source B is anchored to end-of-line so it cannot match A's longer
         "Index <n> is out of bounds of the <ord> dimension of array ...,
         <path>:<line>.<col>" -- the two share a prefix but diverge after
         "bounds".
      4. Source C is matched positively from its closed vocabulary.
      5. Anything left that fired an assertion is `unattributed`.
    """
    assessment = bool(RE_ASSESSMENT.search(text))
    shape = bool(RE_SHAPE_CHECK.search(text))
    lib = bool(RE_LIB_SANITY.search(text))
    rtc = bool(RE_RTC.search(text))
    rtlib = bool(RE_RUNTIME_LIB.search(text))
    oracle = bool(RE_ORACLE_MSG.search(text))
    any_assert = bool(RE_ASSERT.search(text))
    passed = bool(RE_PASSED.search(text))

    if assessment or shape:
        # Source A. A guard firing means the access or the shape was wrong, so
        # the run cannot also have passed; if both markers are present the
        # assessment wins because it is the more specific evidence.
        return "detector", passed
    if lib:
        # Ungated library sanity check on the same prefix as A-host. choreo
        # shipped it but the assessor did not produce it.
        return "runtime_lib", passed
    if rtc:
        # A `runtime check failed` line that is neither a known assessment nor a
        # known library check. Do NOT assume it is an assessment: that is the
        # inference that credited allocation failures to the assessor. Surface
        # it instead.
        return "unattributed", passed
    if rtlib:
        return "runtime_lib", passed
    if oracle:
        return "oracle", passed
    if any_assert:
        # An assertion fired but matches no known vocabulary. Surface it rather
        # than guessing which mechanism to credit.
        return "unattributed", passed
    if passed:
        return "none", True
    return "crash" if rc not in (0,) else "none", passed


def classify_one(rec, workdir, keep_logs=True, policy=None):
    """Full E1 pipeline for one mutant. Returns a `mutant` record dict."""
    mid = rec["mutant_id"]
    src = os.path.join(REPO, rec["mutant_path"])
    d = os.path.join(workdir, mid.replace("/", "_"))
    os.makedirs(d, exist_ok=True)

    t0 = time.time()
    out = {
        "toolchain": TOOLCHAIN,
        "category": rec["category"],
        "class": rec["class"],
        "paper_category": rec["paper_category"],
        "mutant_id": mid,
        "level": str(rec["level"]),
        # cross-cutting provenance (statistics-manifest: non-negotiable)
        "settings_hash": rec.get("settings_hash"),
        "kernel_hash": rec.get("kernel_hash"),
        "mutant_hash": rec.get("mutant_hash"),
        "spec": rec["spec"],
        "case": rec["case"],
    }

    if not os.path.exists(src):
        out.update(outcome="n/a", stage="compile", manifest="noop",
                   note="mutant source missing")
        return out

    # Oracle configuration for this exact base case, from calibrate_oracle.py.
    # `use_check` is only true where the unmutated base was observed to PASS its
    # own reference check with -D__CHECK__; `oracle_usable` is false where the
    # base fails, in which case no manifest verdict can be trusted.
    pol = (policy or {}).get(f"{rec['category']}/{rec['case']}")
    if pol is None:
        # No calibration yet: fall back to the static gate list but say so.
        gated = rec["category"] in GATED_CHECK
        usable = True
        out["calibrated"] = False
    else:
        gated = pol["use_check"]
        usable = pol["oracle_usable"]
        out["calibrated"] = True
    out["check_flag"] = gated
    out["oracle_usable"] = usable
    xenv = {"EXTRA_TARGET_CFLAGS": "-D__CHECK__"} if gated else None

    # ---- 1. detector compile -------------------------------------------
    det_sh = os.path.join(d, "det.sh")
    ok, rc, _ = compile_stage(src, COMPILE_FLAGS, det_sh, os.path.join(d, "det.compile.log"))
    out["compile_rc"] = rc

    # ---- 2. oracle build (specs §7 manifest check) ----------------------
    # Done before the detector execute so that a compile-detected mutant still
    # gets a manifest verdict.
    off_sh = os.path.join(d, "off.sh")
    off_ok, off_rc, _ = compile_stage(src, ORACLE_FLAGS, off_sh,
                                      os.path.join(d, "off.compile.log"))
    out["oracle_compile_rc"] = off_rc

    manifest = "noop"
    oracle_note = ""
    infra = None
    if not off_ok:
        # The defect is visible even with obligation checks off: the program is
        # genuinely broken, so it corrupts.
        manifest = "corrupts"
        oracle_note = "oracle compile failed"
    else:
        orc, otext, infra = execute_stage(off_sh, os.path.join(d, "off.run.log"), env=xenv)
        out["oracle_run_rc"] = orc
        caught, passed = classify_log(otext, orc)
        out["oracle_passed"] = passed
        # Recorded separately because it changes what `manifest` means. The
        # manifest is supposed to be INDEPENDENT ground truth from the kernel's
        # own §7 reference check. Two ways that can fail, and they differ in
        # severity:
        #   detector    an ASSESSMENT fired despite --disable-runtime-check.
        #               Should be impossible (both emission sites early-return on
        #               DisableRuntimeCheck); if seen, the flag did not take and
        #               the whole oracle arm is suspect.
        #   runtime_lib ArrayProxy::operator[]'s bounds check fired. EXPECTED --
        #               source B is not gated, and the oracle reads its operands
        #               through ArrayProxy. It means "corrupts" rests partly on a
        #               choreo-provided bounds check, not purely on the harness's
        #               numeric comparison. Not an error, but a conflation a
        #               reader must be able to see rather than have folded away.
        out["oracle_caught"] = caught
        if passed and caught == "none" and orc == 0:
            manifest = "noop"
            oracle_note = "oracle passed: mutant does not corrupt output"
        else:
            manifest = "corrupts"
            oracle_note = f"oracle caught={caught} rc={orc}"
            if caught == "detector":
                oracle_note += (
                    "; ANOMALY: a choreo ASSESSMENT fired in the checks-off "
                    "oracle arm, so --disable-runtime-check did not suppress it "
                    "-- this manifest verdict is not independent of choreo")
            elif caught == "runtime_lib":
                oracle_note += (
                    "; choreo's runtime-library bounds check (ArrayProxy) fired "
                    "in the oracle arm -- expected, it is not gated by "
                    "--disable-runtime-check, but the verdict is then partly "
                    "choreo's rather than purely the harness's")
            elif caught == "unattributed":
                oracle_note += (
                    "; UNRECOGNIZED assertion message -- not matched to the "
                    "assessment, runtime-library, or §7 vocabularies; this "
                    "manifest verdict needs manual review")
    out["manifest"] = manifest
    out["oracle_note"] = oracle_note

    # ---- 3. detector verdict -------------------------------------------
    if not ok:
        out["outcome"] = "compile"
        out["stage"] = "compile"
        out["detector"] = "compile-error"
    else:
        drc, dtext, dinfra = execute_stage(det_sh, os.path.join(d, "det.run.log"), env=xenv)
        infra = infra or dinfra
        out["run_rc"] = drc
        caught, passed = classify_log(dtext, drc)
        out["detector"] = caught
        out["detector_passed"] = passed
        m = RE_EXECTIME.search(dtext)
        if m:
            out["exec_time_us"] = int(m.group(1))
        if caught == "detector":
            # A choreo-generated assessment fired: either the entry-level
            # `runtime_check` (stderr, before the body runs) or a site assertion
            # rendered from a semacheck template (stdout, at the access). Both
            # are the assessor's verdict, so both count as detected. Which of the
            # two spoke is recoverable from the run log if the entry/interior
            # split is ever needed.
            out["outcome"] = "runtime"
            out["stage"] = "runtime"
        else:
            # runtime_lib / oracle / unattributed / crash / clean pass: the
            # assessor did not speak, so choreo did not detect it. Note that
            # `runtime_lib` is choreo-provided code but is NOT an assessor
            # output -- it is an ungated defensive check in the container
            # accessor, present in the checks-off build too, so counting it as a
            # detection would credit the assessor with work the static analysis
            # never did. It stays distinguishable via the `detector` field.
            out["outcome"] = "never"
            out["stage"] = "runtime"

    if infra:
        # Verdict is untrustworthy: the program never ran to the point where a
        # detector could speak. Flag it loudly instead of reporting a number.
        out["infra_error"] = infra
        out["outcome"] = "n/a"
        out["note"] = f"infrastructure failure, verdict void: {infra}"
    elif not usable:
        # The base kernel fails its own reference check, so a mutant's failure
        # is not evidence of corruption. Detection verdicts are still valid
        # (choreo's obligation checks are independent of the reference), but the
        # manifest field cannot be decided. Mark it rather than guess.
        out["note"] = ("manifest undecidable: unmutated base fails its own "
                       "reference check (see raw/oracle_policy.json)")
        out["manifest"] = "noop"

    out["wall_s"] = round(time.time() - t0, 2)

    if not keep_logs:
        for f in os.listdir(d):
            if f.endswith(".log"):
                os.remove(os.path.join(d, f))
    out["log_dir"] = os.path.relpath(d, REPO)
    return out


def reproject_one(rec, workdir):
    """Re-derive the classifier-dependent fields of an EXISTING record from the
    retained run logs, without invoking choreo or nvcc.

    Why this exists. `classify_log` is the single place where a log becomes a
    verdict, and it has now been corrected twice. A full E1 re-run costs nvcc
    for 120 mutants x 2 arms (~12 s each) purely to re-read text that is already
    on disk under `raw/e1_logs/<mid>/`. Worse, it re-runs on a shared host, so
    it competes for CPU with whatever timing lane is measuring. Re-projection
    gets the same answer for free and, because the inputs are frozen, makes the
    before/after diff exact rather than confounded by a second execution.

    Only fields DERIVED FROM LOG TEXT are recomputed. Provenance (hashes, spec,
    case), build results (compile_rc, oracle_compile_rc, run_rc, oracle_run_rc)
    and the calibration policy are taken from the existing record as-is.
    """
    mid = rec["mutant_id"]
    d = os.path.join(workdir, mid.replace("/", "_"))
    out = dict(rec)
    out["reprojected"] = True

    def read(name):
        p = os.path.join(d, name)
        if not os.path.exists(p):
            return None
        with open(p, errors="replace") as f:
            return f.read()

    # ---- oracle arm ------------------------------------------------------
    # Mirrors classify_one's §7 block. `oracle_compile_rc != 0` short-circuits
    # to corrupts without a log, exactly as the original does.
    # `or 0` because a record written by an older harness may carry None, and
    # `None != 0` is True -- that would silently reclassify a clean oracle build
    # as "oracle compile failed".
    if (rec.get("oracle_compile_rc") or 0) != 0:
        manifest, note = "corrupts", "oracle compile failed"
    else:
        otext = read("off.run.log")
        if otext is None:
            out["reproject_error"] = "off.run.log missing; oracle arm not reprojected"
            return out
        orc = rec.get("oracle_run_rc", 0)
        caught, passed = classify_log(otext, orc)
        out["oracle_passed"] = passed
        out["oracle_caught"] = caught
        if passed and caught == "none" and orc == 0:
            manifest = "noop"
            note = "oracle passed: mutant does not corrupt output"
        else:
            manifest = "corrupts"
            note = f"oracle caught={caught} rc={orc}"
            if caught == "detector":
                note += ("; ANOMALY: a choreo ASSESSMENT fired in the checks-off "
                         "oracle arm, so --disable-runtime-check did not suppress "
                         "it -- this manifest verdict is not independent of choreo")
            elif caught == "runtime_lib":
                note += ("; choreo's runtime-library bounds check (ArrayProxy) "
                         "fired in the oracle arm -- expected, it is not gated by "
                         "--disable-runtime-check, but the verdict is then partly "
                         "choreo's rather than purely the harness's")
            elif caught == "unattributed":
                note += ("; UNRECOGNIZED assertion message -- not matched to the "
                         "assessment, runtime-library, or §7 vocabularies; this "
                         "manifest verdict needs manual review")

    # ---- detector arm ----------------------------------------------------
    if (rec.get("compile_rc") or 0) != 0:
        outcome, stage, detector = "compile", "compile", "compile-error"
    else:
        dtext = read("det.run.log")
        if dtext is None:
            out["reproject_error"] = "det.run.log missing; detector arm not reprojected"
            return out
        drc = rec.get("run_rc") or 0
        caught, passed = classify_log(dtext, drc)
        detector = caught
        out["detector_passed"] = passed
        if caught == "detector":
            outcome, stage = "runtime", "runtime"
        else:
            outcome, stage = "never", "runtime"

    # The `oracle_usable=False` override in classify_one wins over the arm
    # result: an unusable reference means no manifest verdict can be trusted.
    # Preserve it rather than silently re-deciding.
    if rec.get("oracle_usable") is False:
        manifest = "noop"
        out["note"] = rec.get("note") or (
            "manifest undecidable: unmutated base fails its own reference check "
            "(see raw/oracle_policy.json)")

    out["manifest"] = manifest
    out["oracle_note"] = note
    out["outcome"] = outcome
    out["stage"] = stage
    out["detector"] = detector
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jobs", type=int, default=6,
                    help="parallel workers; E1 is a correctness lane so GPUs are "
                         "shared freely (manifest §6)")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--only", default="", help="restrict to one class, e.g. M1")
    ap.add_argument("--manifest", default=MANIFEST_IN)
    ap.add_argument("--policy", default=ORACLE_POLICY)
    ap.add_argument("--out", default=os.path.join(RAW, "e1_mutant_records.json"))
    ap.add_argument("--workdir", default=os.path.join(RAW, "e1_logs"))
    ap.add_argument("--device", default=os.environ.get("CUDA_VISIBLE_DEVICES", "0"),
                    help="GPU index, recorded as gpu_device on every record "
                         "(schema requirement); E1 is a correctness lane so the "
                         "GPU is shared freely, exclusive=false")
    ap.add_argument("--no-logs", action="store_true")
    ap.add_argument("--reproject", action="store_true",
                    help="re-derive verdicts from the retained run logs under "
                         "--workdir instead of recompiling. Use after editing "
                         "classify_log: it costs no nvcc, does not disturb the "
                         "GPU, and makes the before/after diff exact. Reads the "
                         "existing --out file and rewrites it in place.")
    a = ap.parse_args()

    # MUST be absolute: run() executes choreo with cwd=REPO, so a relative
    # scratch path resolves against the repo root and choreo reports
    # "The input file ... does not exist" (rc=1) for every case.
    a.workdir = os.path.abspath(a.workdir)
    a.out = os.path.abspath(a.out)
    a.manifest = os.path.abspath(a.manifest)
    a.policy = os.path.abspath(a.policy)

    if not os.path.exists(CHOREO):
        print(f"ERROR: choreo binary not found at {CHOREO}", file=sys.stderr)
        print("       run `benchmark2/choreo/run.sh setup` first", file=sys.stderr)
        return 2

    data = json.load(open(a.manifest))
    recs = data["mutants"]
    if a.only:
        recs = [r for r in recs if r["class"] == a.only]
    if a.limit:
        recs = recs[:a.limit]

    os.makedirs(a.workdir, exist_ok=True)
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    # Print the full identity block (binary sha/mtime vs checkout HEAD) so a
    # stale-binary mismatch is visible in the run log, not just buried in the
    # records. `ver` is the binary's source commit — what the data actually came
    # from — which is what every record's toolchain_version must carry.
    idt = toolchain.describe()
    ver = idt["version"]

    policy = None
    if os.path.exists(a.policy):
        policy = json.load(open(a.policy))["policy"]
        bad = [k for k, v in policy.items() if not v["oracle_usable"]]
        print(f"[choreo] oracle policy: {len(policy)} cases, "
              f"{len(bad)} with an unusable reference")
    else:
        print(f"[choreo] WARNING: no {os.path.relpath(a.policy, REPO)} — run "
              f"calibrate_oracle.py first; manifest verdicts will be guesses",
              file=sys.stderr)

    print(f"[choreo] E1: classifying {len(recs)} mutants with {a.jobs} workers "
          f"(croqtile @ {ver or 'unknown'})")

    # ---- re-projection: no compile, no execute, no GPU -------------------
    if a.reproject:
        if not os.path.exists(a.out):
            print(f"ERROR: --reproject needs an existing record file at "
                  f"{os.path.relpath(a.out, REPO)}", file=sys.stderr)
            return 2
        prev = json.load(open(a.out))
        # The E1 artifact stores its rows under "records" (see the json.dump at
        # the end of main). Reading "results" here would find nothing, skip every
        # mutant, and then write a key collect.py has never heard of -- a silent
        # empty artifact. Accept both so a hand-edited file still works.
        if isinstance(prev, dict):
            prev_rows = prev.get("records") or prev.get("results") or []
        else:
            prev_rows = prev
        by_id = {r["mutant_id"]: r for r in prev_rows}
        results = []
        changed = collections.Counter()
        for r in recs:
            old = by_id.get(r["mutant_id"])
            if old is None:
                print(f"  [skip] {r['mutant_id']}: not in existing records",
                      file=sys.stderr)
                continue
            new = reproject_one(old, a.workdir)
            for f in ("outcome", "stage", "manifest", "detector", "oracle_caught"):
                if new.get(f) != old.get(f):
                    changed[f] += 1
                    print(f"  [DIFF] {new['mutant_id']:<26} {f}: "
                          f"{old.get(f)!r} -> {new.get(f)!r}")
            if new.get("reproject_error"):
                print(f"  [WARN] {new['mutant_id']}: {new['reproject_error']}",
                      file=sys.stderr)
            results.append(new)
        results.sort(key=lambda x: (x["class"], x["category"], x["mutant_id"]))
        # Preserve the original envelope (produced_by, elapsed_s, gpu_device,
        # exclusive, pinned_flags) so downstream readers see no schema drift, and
        # keep the row list under "records".
        payload = dict(prev) if isinstance(prev, dict) else {}
        payload.pop("results", None)
        payload.update({"toolchain": TOOLCHAIN, "toolchain_version": ver,
                        "toolchain_identity": idt, "records": results,
                        "reprojected": True})
        with open(a.out, "w") as f:
            json.dump(payload, f, indent=1)
        print(f"\n[choreo] reprojected {len(results)} records -> "
              f"{os.path.relpath(a.out, REPO)}")
        print(f"[choreo] field changes: {dict(changed) or 'NONE'}")
        return 0

    results = []
    t0 = time.time()
    with cf.ThreadPoolExecutor(max_workers=a.jobs) as ex:
        futs = {ex.submit(classify_one, r, a.workdir, not a.no_logs, policy): r
                for r in recs}
        for i, fut in enumerate(cf.as_completed(futs), 1):
            r = futs[fut]
            try:
                res = fut.result()
            except Exception as e:                      # keep the lane alive
                res = {"toolchain": TOOLCHAIN, "category": r["category"],
                       "class": r["class"], "paper_category": r["paper_category"],
                       "mutant_id": r["mutant_id"], "level": str(r["level"]),
                       "outcome": "n/a", "stage": "compile", "manifest": "noop",
                       "note": f"harness exception: {e!r}"}
            res["toolchain_version"] = ver
            # E1 is a correctness lane: manifest §6 lets it share the GPU, so
            # exclusive=false. No cost/residue/latency record is produced here.
            res["gpu_device"] = str(a.device)
            res["exclusive"] = False
            results.append(res)
            print(f"  [{i:>3}/{len(recs)}] {res['mutant_id']:<26} "
                  f"outcome={res['outcome']:<8} stage={res['stage']:<8} "
                  f"manifest={res['manifest']:<9} detector={res.get('detector','-')}",
                  flush=True)

    # stable order: class, then category, then mutant_id
    results.sort(key=lambda x: (x["class"], x["category"], x["mutant_id"]))
    with open(a.out, "w") as f:
        json.dump({"toolchain": TOOLCHAIN, "toolchain_version": ver,
                   "toolchain_identity": idt,
                   "produced_by": "minimal", "elapsed_s": round(time.time() - t0, 1),
                   "gpu_device": str(a.device), "exclusive": False,
                   "pinned_flags": {"compile": COMPILE_FLAGS,
                                    "oracle": ORACLE_FLAGS},
                   "records": results}, f, indent=1)

    # ---- report ---------------------------------------------------------
    print(f"\n[{choreo_tag()}] wrote {len(results)} records -> "
          f"{os.path.relpath(a.out, REPO)}  ({round(time.time()-t0,1)}s)")
    print(f"\n{'class':<6}{'compile':>9}{'runtime':>9}{'never':>7}{'n/a':>6}"
          f"{'corrupts':>10}{'noop':>6}")
    for cls in ("M1", "M2", "M3"):
        sub = [r for r in results if r["class"] == cls]
        c = collections.Counter(r["outcome"] for r in sub)
        mf = collections.Counter(r["manifest"] for r in sub)
        print(f"{cls:<6}{c['compile']:>9}{c['runtime']:>9}{c['never']:>7}"
              f"{c['n/a']:>6}{mf['corrupts']:>10}{mf['noop']:>6}")
    tot = collections.Counter(r["outcome"] for r in results)
    mft = collections.Counter(r["manifest"] for r in results)
    print(f"{'ALL':<6}{tot['compile']:>9}{tot['runtime']:>9}{tot['never']:>7}"
          f"{tot['n/a']:>6}{mft['corrupts']:>10}{mft['noop']:>6}")

    noops = [r["mutant_id"] for r in results if r["manifest"] == "noop"]
    if noops:
        print(f"\nDISCARD (manifest=noop, specs §11.1): {len(noops)}")
        for m in noops:
            print(f"  {m}")

    infra = [r for r in results if r.get("infra_error")]
    if infra:
        print(f"\nINFRASTRUCTURE FAILURES (verdicts void, fix the harness): "
              f"{len(infra)}")
        for r in infra:
            print(f"  {r['mutant_id']:<26} {r['infra_error']}")
    # S2 sanity: choreo detects every mutant before the device is reached.
    before_device = tot["compile"] + tot["runtime"]
    print(f"\nS2 (before-device detections): {before_device}/{len(results)}"
          f"   never={tot['never']}")
    if tot["never"]:
        print("  never-detected mutants (oracle caught them, choreo did not):")
        for r in results:
            if r["outcome"] == "never":
                print(f"    {r['mutant_id']:<26} {r['class']}/{r['category']:<22}"
                      f" detector={r.get('detector')}")
    return 0


def choreo_tag():
    return "choreo"


if __name__ == "__main__":
    sys.exit(main())
